services:
  autofacil-client:
    image: node:20  # Imagem Node para o projeto Angular
    working_dir: /app
    volumes:
      - ./AutoFacil.Client:/app
      - /app/node_modules
    ports:
      - "4200:4200"  # Porta 4200 do container exposta para 4200 no host
    command: >
      sh -c "npm install && npm run start -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true

  autfacil-api:
    image: autofacil-api
    build:
      context: .  # Diretório de contexto de build
      dockerfile: ./AutoFacil.Server/Dockerfile  # Caminho correto para o Dockerfile
    ports:
      - "5000:80"   # Porta 80 do container exposta para 5000 no host (API)
      - "7106:7106" # Se você estiver utilizando outra porta para algum serviço (ex: SignalR ou outra comunicação)
      - "5234:5234" # Se houver alguma outra porta necessária, mapeie aqui
      - "46781"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./AutoFacil.Server:/src  # Monta a pasta do servidor no container
    networks:
      - autfacil-network

networks:
  autfacil-network:
    driver: bridge
